### ISSUE TITLE
Unable to use the pagination

### ISSUE THREAD

**Issue by ummesulaith** [softrunapp/Paginated-RecyclerView#2]
Unable to implement this library using gridLayoutManager and in fragment using data-binding.

**Comment by softrunapp** [comment]
Hi,
don't use adapter.setDefaultRecyclerView(this,R.id.recycler_view) when you want to use GrailLayoutManager in RecyclerView.

You must define your RecyclerView in code with findViewById() and set GradLayoutManager to them and then call setRecyclerView() method in PaginatedAdapter like this:

`RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new GridLayoutManager(this,2));
        adapter.setRecyclerView(recyclerView);`

**Comment by softrunapp** [comment]
> Unable to implement this library using gridLayoutManager and in fragment using data-binding.

Hi,
Don't use adapter.setDefaultRecyclerView(this,R.id.recycler_view) when you want to use GrailLayoutManager in RecyclerView.

You must define your RecyclerView in code with findViewById() and set GradLayoutManager to them and then call setRecyclerView() method in PaginatedAdapter like this:

`RecyclerView recyclerView = findViewById(R.id.recyclerView);`
 `recyclerView.setLayoutManager(new GridLayoutManager(context,2));`
 `adapter.setRecyclerView(recyclerView);`
